name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: telus-koodo
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          
      - name: Authenticate Docker
        run: gcloud auth configure-docker
        
      - name: Build and Push
        run: |
          docker build -t gcr.io/telus-koodo/portfolio-builder .
          docker push gcr.io/telus-koodo/portfolio-builder
          
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy portfolio-builder \
            --image gcr.io/telus-koodo/portfolio-builder \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
