name: Deploy React App to Cloud Run

on:
  push:
    branches: [main]  # or your working branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install
      working-directory: my-flexi-profile-backup

    - name: Build React App
      run: npm run build
      working-directory: my-flexi-profile-backup

    - name: Copy Build Files
      run: |
        cp -r my-flexi-profile-backup/build ./build

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build Docker Image
      run: |
        docker build -t us-central1-docker.pkg.dev/telus-koodo/react-app-repo/react-app:$GITHUB_SHA .

    - name: Push Docker Image
      run: |
        docker push us-central1-docker.pkg.dev/telus-koodo/react-app-repo/react-app:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy react-app \
          --image us-central1-docker.pkg.dev/telus-koodo/react-app-repo/react-app:$GITHUB_SHA \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --port 80
