name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

env:
  SERVICE_NAME: portfolio-builder
  REGION: us-central1
  WORKING_DIR: my-flexi-profile-backup

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Verify working directory
        run: |
          cd ${{ env.WORKING_DIR }}
          echo "Current working directory: $(pwd)"
          ls -la
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: 'Authenticate to Google Cloud'
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > ${{ github.workspace }}/${{ env.WORKING_DIR }}/key.json
          gcloud auth activate-service-account --key-file=${{ github.workspace }}/${{ env.WORKING_DIR }}/key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Build Docker image
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          echo "Building Docker image locally..."
          docker build -t ${{ env.SERVICE_NAME }}:latest .
          echo "Docker build completed"
          
      - name: Deploy to Cloud Run
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          echo "Submitting build to Cloud Run..."
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --source . \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated

      - name: Show Service URL
        run: |
          echo "Deployed service URL:"
          gcloud run services describe ${{ env.SERVICE_NAME }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --format='value(status.url)'
