name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: telus-koodo
  SERVICE_NAME: portfolio-builder
  REGION: us-central1
  WORKING_DIR: my-flexi-profile-backup

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Verify working directory
        run: |
          cd ${{ env.WORKING_DIR }}
          echo "Current working directory: $(pwd)"
          ls -la
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate Docker
        run: |
          gcloud auth configure-docker
          echo "Docker authentication completed"
        
      - name: Build and Push
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          echo "Building from directory: $(pwd)"
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }} .
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}
          
      - name: Deploy to Cloud Run
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated

      - name: Show Service URL
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          echo "Deployed service URL:"
          gcloud run services describe ${{ env.SERVICE_NAME }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --format='value(status.url)'
